library(dplyr)
library(ggplot2)
library(tidyr)
library(readr)
library(moments)
library(lubridate)
install.packages("moments")
library(moments)
setwd("/Users/manuelagranadoshernandez/Documents/GitHub/caso-1/")
cost_path <- "hoja1caso.csv"
read.csv(caso_path)
